### ISSUE TITLE
Path with multiple double-dots not matched

### ISSUE THREAD

**Issue by pugnascotia** [jonschlinkert/micromatch#81]
Here is a test case that I thought should pass but doesn't (including `nanomatch` for completeness):

```
var micromatch = require('micromatch');
var nanomatch = require('nanomatch');

var glob = '**/__tests__/**/*.js';

var path = '/path/to/__tests__/foo/bar/baz/../../../test.js';

var microResult = micromatch(path, glob);
var nanoResult = nanomatch(path, glob);

console.log('micromatch ' + (microResult.length > 0 ? 'passed' : 'failed'));
console.log('nanomatch ' + (nanoResult.length > 0 ? 'passed' : 'failed'));
```

Result:

```
micromatch failed
nanomatch failed
```

Am I misunderstanding how `**` works in this context?

**Comment by jonschlinkert** [comment]
is this a theoretical test? how is a valid path like that created?

**Comment by jonschlinkert** [comment]
oh, sorry - there were two problems with my initial review. For some reason my brain told me that `/__tests__/` was `/../tests/../`, which is part of the reason I was confused about how a path like that would exist. Then I forgot to answer your actual question. 

> Am I misunderstanding how ** works in this context?

Yes. `../` should never be matched by `**` because it can cause infinite recursion.

**Comment by pugnascotia** [comment]
Ah, of course it would - thanks.

**Comment by jonschlinkert** [comment]
No problem, it was a totally valid question with a not-so-obvious answer IMO. If you're interested, there is also a [code comment in minimatch](https://github.com/isaacs/minimatch/blob/master/minimatch.js#L817-L818) speaks to this.
